package com.task.dms.presistence.models;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnoreType;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "department", catalog = "dmstask")
// @JsonIgnoreType
public class Department implements java.io.Serializable {

    private Integer code;
    private String name;
    private String description;
    private Set<Employee> employees = new HashSet<Employee>(0);

    public Department() {
    }

    public Department(Integer code) {
        this.code = code;
    }

    public Department(Integer code, String name, String description, Set<Employee> employees) {
        this.code = code;
        this.name = name;
        this.description = description;
        this.employees = employees;
    }

    @Id

    @Column(name = "code", unique = true, nullable = false)
    public Integer getCode() {
        return this.code;
    }

    public void setCode(Integer code) {
        this.code = code;
    }

    @Column(name = "name", length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "description", length = 45)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    // @JsonManagedReference
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "department")
    public Set<Employee> getEmployees() {
        return this.employees;
    }

    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }

}
