package com.task.dms.presistence.models;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name="employee"
    ,catalog="dmstask"
)
public class Employee  implements java.io.Serializable {


     private int code;
     private Department department;
     private String name;
     private Date birthDate;
     private String address;
     private String mobile;
     private Double salary;

    public Employee() {
    }

	
    public Employee(int code) {
        this.code = code;
    }
    public Employee(int code, Department department, String name, Date birthDate, String address, String mobile, Double salary) {
       this.code = code;
       this.department = department;
       this.name = name;
       this.birthDate = birthDate;
       this.address = address;
       this.mobile = mobile;
       this.salary = salary;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="department")
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="birth_date", length=10)
    @JsonFormat(pattern="yyyy-MM-dd")
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    
    @Column(name="address", length=45)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="mobile", length=45)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    
    @Column(name="salary", precision=22, scale=0)
    public Double getSalary() {
        return this.salary;
    }
    
    public void setSalary(Double salary) {
        this.salary = salary;
    }




}

